// <auto-generated />
using System;
using FileDownloader.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileDownloader.DataAccess.Migrations
{
    [DbContext(typeof(FileDownloadContext))]
    [Migration("20190716115504_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FileDownloader.DataAccess.Model.DownloadLog", b =>
                {
                    b.Property<int>("DownloadLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BytesTotal");

                    b.Property<int>("DownloadSpeedInKiloBytesPerSecond");

                    b.Property<string>("DownloadState");

                    b.Property<TimeSpan>("DownloadTime");

                    b.Property<string>("Error");

                    b.Property<string>("FileSource");

                    b.Property<bool>("IsFileBig");

                    b.Property<bool>("IsSpeedSlow");

                    b.Property<string>("LocalFilePath");

                    b.Property<string>("Protocol");

                    b.HasKey("DownloadLogId");

                    b.ToTable("DownloadLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
